<?php

/**
 * @file
 * Contains custom_login.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_login_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_login module.
    case 'help.page.custom_login':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides customized login functionality.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function custom_login_theme() {
  return [
    'custom-login' => [
      'variables' => ['form' => null],
    ],
  ];
}

function custom_login_mail($key, &$message, $params) {
  $options = array(
    'langcode' => $message['langcode'],
  );
  $message['headers']['MIME-Version'] = '1.0';
  $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';
  $message['headers']['Content-Transfer-Encoding'] = '8Bit';
  $message['headers']['X-Mailer'] = 'Drupal';
  $message['from'] = \Drupal::config('system.site')->get('mail');
  switch ($key) {
    case 'custom_login_2fa':
      $message['subject'] = t('2 FA Code');
      $message['body'][] = $params['message'];
    break;
  }
}
